services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PW:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: ['redis-server', '--save', '', '--appendonly', 'no']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672' # AMQP
      - '15672:15672' # page
    restart: always
    hostname: rabbitmq-server
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PW}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt && rabbitmq-server"
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'check_running']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    restart: always
    network_mode: 'host'
    env_file:
      - .env
    environment:
      - COTURN_STUN_PORT=3478
      - COTURN_TURN_PORT=3478
      - COTURN_MIN_PORT=49152
      - COTURN_MAX_PORT=65535
      - COTURN_REALM=${TURN_REALM}
      - COTURN_USER=${TURN_USER}


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'
    restart: always

volumes:
  postgres_data:
  rabbitmq_data:
  prometheus_data:

networks:
  app-network:
    driver: bridge
