export const ERR_CODE = {
  INIT_DEVICE: 1000,

  AMQT_PARSE_ERROR: 2000,
  AMQT_UNKNOWN_TYPE: 2001,
  AMQT_NULL_CANDIDATE: 2002,
  AMQT_NULL_OFFER: 2003,
  AMQT_OFFER_TIMEOUT: 2004,
  AMQT_CHANNEL_CLOSE: 2005,
  AMQT_CONNECTION_CLOSE: 2006,

  FFMPEG_SPAWN: 3000,
  FFMPEG_KILL_SIGNAL: 3001,

  UDP_CLOSE: 4000,
  UDP_ERR: 4001,

  WEBRTC_CLOSE: 5000,
} as const;

export const ERR_MSG = {
  [ERR_CODE.INIT_DEVICE]: "Failed to initialize device",

  [ERR_CODE.AMQT_PARSE_ERROR]: "AMQT Parse Error",
  [ERR_CODE.AMQT_UNKNOWN_TYPE]: "AMQT Unknown Type",
  [ERR_CODE.AMQT_NULL_CANDIDATE]: "AMQT Null Candidate",
  [ERR_CODE.AMQT_NULL_OFFER]: "AMQT Null Offer",
  [ERR_CODE.AMQT_OFFER_TIMEOUT]: "AMQT Offer Timeout",
  [ERR_CODE.AMQT_CHANNEL_CLOSE]: "AMQT Channel Close",
  [ERR_CODE.AMQT_CONNECTION_CLOSE]: "AMQT Connection Close",

  [ERR_CODE.FFMPEG_SPAWN]: "FFMPEG Spawn Error",
  [ERR_CODE.FFMPEG_KILL_SIGNAL]: "FFMPEG Kill Signal Error",

  [ERR_CODE.UDP_CLOSE]: "UDP Close",
  [ERR_CODE.UDP_ERR]: "UDP Error",

  [ERR_CODE.WEBRTC_CLOSE]: "WebRTC Close",
} as const;